name: build pages

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :0
      PYTEST_ADDOPTS: "--color=yes" # colors in pytest
      GLCONTEXT_WIN_LIBGL: C:\msys64\mingw64\bin\opengl32.dll
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install and cache ffmpeg (all OS)
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-full tipa python-opengl libpango1.0-dev
          version: 1.0

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt -y install texlive-full tipa python-opengl libpango1.0-dev
          # sudo apt-get -y install texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa python-opengl libpango1.0-dev xvfb
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          # # start xvfb in the background
          # sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      
      - name: Install Environment
        run: |
          pip install -r requirements.txt

      - name: Run Manim
        run: | 
          manim -qh -a --save_sections slides.py

      - name: Run the Manim Editor
        run: |
          mkdir pages
          cd pages
          manedit --project_name PG-NER \
            --quick_present_export ../media/videos/slides/1080p60/sections/NamedEntityRecognition1_1.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/Problem1_2.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/Motivation1_3.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/OldWorkingPrinciple2_1.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/NewWorkingPrinciple2_2.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/AscendingIndexWordEmbedding2_3.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/OneHotWordEmbedding2_4.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/OneHotWordEmbeddingPlot2_5.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/WordEmbedding2_6.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/WordEmbedding2_7.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/Datsets3_1.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/Datsets3_2.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/Frameworks3_3.json \
            --quick_present_export ../media/videos/slides/1080p60/sections/ChallengesWithHistoricalData4_1.json

      - name: Create Redirect
        run: echo "<head><meta http-equiv='refresh' content='0; URL=PG-NER/index.html'></head>" > pages/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: pages
